# aws cloudformation create-stack  --stack-name RDSstack --region us-east-1 --template-body file://RDStemplate.yml --parameters file://RDStemplate-parameters.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
  DBName:
    Default: mydb
    Description: My database
    Type: String
  DBInstanceClass:
    Default: db.m5.large
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '50'
    Type: Number
    Description: The size of the database (GiB)

  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    Default: 'UdacityDem0'

  DBUsername:
    NoEcho: 'true'
    Default: admin
    Description: Username for MySQL database access
    Type: String

Resources:
  myDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      VPCSecurityGroups: [sg-01057d83b89ef5522]
      PubliclyAccessible: false
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.16"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MonitoringInterval: '60'
      # MonitoringRoleArn: 'arn:aws:iam::123456789012:role/rds-monitoring-role'
      MonitoringRoleArn: 'arn:aws:iam::040784598029:role/rds-monitoring-role'
    DeletionPolicy: Retain

  myDBSubnetGroup: 
    Properties: 
      DBSubnetGroupName: "Subnet Group"
      DBSubnetGroupDescription: my description
      SubnetIds: 
        - subnet-0c26351ee803a6767
        - subnet-09f8d177e313b1c07
      Tags: 
        - 
          Key: String
          Value: String
    Type: AWS::RDS::DBSubnetGroup